<a href="https://colab.research.google.com/github/Sofiiasmm/-_-/blob/main/%D0%A1%D1%83%D1%88%D0%BA%D0%BE_%D0%BF%D1%80_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#варіант 18
#завд 1 Створіть одновимірний масив (вектор) з числами, які є кубами натуральних чисел,
#починаючи з 1, та виведіть його значення.

import numpy as np
N = 10
cubes = np.array([x**3 for x in range(1, N+1)])

print("Масив кубів натуральних чисел:")
print(cubes)
print("              ")

#завд 2 Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його значеннями
#факторіалів перших натуральних чисел
import numpy as np
import math

#список з факторіалами чисел від 1 до 9
factorials = [math.factorial(i) for i in range(1, 10)]

#перетворення списку у матрицю 3x3
matrix = np.array(factorials).reshape((3, 3))

print("Матриця 3x3 з факторіалами чисел від 1 до 9:")
print(matrix)
print("              ")

#завд 3 Створіть масив розміром 3x3, заповніть його випадковими цілими числами від -5 до 5
#та знайдіть суму модулів кожного рядка.
import numpy as np

#матриця 3x3 з випадковими числами від -5 до 5
A = np.random.randint(-5, 6, (3,3))
print("Матриця:\n", A)

#сума модулів кожного рядка
row_sums = np.sum(np.abs(A), axis=1)
print("Сума модулів кожного рядка:", row_sums)
print("              ")

#завд 4 Створіть масив розміром 3x3, заповніть його випадковими дійсними числами в
#діапазоні від 0 до 1 та знайдіть середнє геометричне всіх елементів
import numpy as np

#матриця 3x3 з випадковими дійсними числами в діапазоні [0,1)
A = np.random.rand(3,3)
print("Матриця:\n", A)
n = A.size

#середнє геометричне
geom_mean = np.prod(A) ** (1/n)

print("Середнє геометричне всіх елементів:", geom_mean)
print("              ")

#завд 5 Створіть два одновимірних масиви розміром 5, заповніть їх випадковими дійсними
#числами від 0 до 1 та виконайте на них поелементні операції додавання, віднімання та
#множення
import numpy as np

#два одновимірні масиви розміром 5 з випадковими дійсними числами [0;1)
a = np.random.rand(5)
b = np.random.rand(5)

print("Масив a:", a)
print("Масив b:", b)

#поелементні операції
print("Додавання:", a + b)
print("Віднімання:", a - b)
print("Множення:", a * b)
print("              ")

#завд 6 Cтворіть дві матриці 3x3, заповніть їх довільними цілими числами від 1 до 5 та
#знайдіть їх добуток.
import numpy as np

#дві матриці 3x3 з випадковими цілими числами від 1 до 5
A = np.random.randint(1, 6, (3,3))
B = np.random.randint(1, 6, (3,3))

print("Матриця A:\n", A)
print("Матриця B:\n", B)

#добуток матриць
C = A @ B
print("Добуток A * B:\n", C)
print("              ")

#завд 7 Створіть дві матриці розміром 2x3 та 3x2, заповніть їх випадковими цілими числами
#в діапазоні від 1 до 5 та перемножте їх між собою
import numpy as np

#матриця 2x3 та 3x2 з випадковими цілими числами від 1 до 5
A = np.random.randint(1, 6, (2,3))
B = np.random.randint(1, 6, (3,2))

print("Матриця A (2x3):\n", A)
print("Матриця B (3x2):\n", B)

#перемноження матриць
C = A @ B
print("Добуток A * B (2x2):\n", C)
print("              ")

#завд 8 Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні
#від 1 до 15 та знайдіть її обернену матрицю
import numpy as np

#матриця 3x3 з випадковими цілими числами від 1 до 15
A = np.random.randint(1, 16, (3,3))
print("Матриця A:\n", A)

#чи матриця є виродженою (det != 0)
det = np.linalg.det(A)
print("Детермінант:", det)

if det != 0:
    inv_A = np.linalg.inv(A)
    print("Обернена матриця A^(-1):\n", inv_A)
else:
    print("Обернена матриця не існує (детермінант = 0).")
print("              ")

#завд 9 Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в
#діапазоні від 0 до 10 та транспонуйте її.
import numpy as np

#матриця 4x4 з випадковими дійсними числами в діапазоні [0;10)
A = np.random.rand(4,4) * 10
print("Матриця A:\n", A)

#транспонування
A_T = A.T
print("Транспонована матриця A^T:\n", A_T)
print("              ")

#завд 10 Створіть матрицю розміром 3x4 та вектор розміром 4x1, заповніть матрицю
#випадковими дійсними числами від 0 до 1, а вектор - випадковими дійсними числами
#від 0 до 1, і знайдіть добуток матриці на вектор.
import numpy as np

#матриця 3x4 з випадковими дійсними числами [0;1)
A = np.random.rand(3,4)
print("Матриця A (3x4):\n", A)

#вектор-стовпчик 4x1
v = np.random.rand(4,1)
print("Вектор v (4x1):\n", v)

#добуток матриці на вектор
result = A @ v
print("Добуток A * v (3x1):\n", result)
print("              ")

#завд 11 Створіть матрицю розміром 2x3 та вектор розміром 3x1,
#заповніть матрицю випадковими дійсними числами від 0 до 1, а
#вектор - випадковими дійсними числами від 0 до 1, і знайдіть добуток матриці на вектор
import numpy as np

#матриця 2x3 з випадковими дійсними числами [0;1)
A = np.random.rand(2,3)
print("Матриця A (2x3):\n", A)

#вектор-стовпчик 3x1
v = np.random.rand(3,1)
print("Вектор v (3x1):\n", v)

#добуток матриці на вектор
result = A @ v
print("Добуток A * v (2x1):\n", result)
print("              ")

#завд 12 Створіть дві матриці розміром 3x3, заповніть їх випадковими цілими числами в
#діапазоні від 1 до 10 та знайдіть суму елементів діагоналі обох матриць (окремо).

import numpy as np

#дві матриці 3x3 з випадковими цілими числами від 1 до 10
A = np.random.randint(1, 11, (3,3))
B = np.random.randint(1, 11, (3,3))

print("Матриця A:\n", A)
print("Матриця B:\n", B)

#сума елементів головної діагоналі
sum_diag_A = np.trace(A)
sum_diag_B = np.trace(B)

print("Сума діагоналі матриці A:", sum_diag_A)
print("Сума діагоналі матриці B:", sum_diag_B)
print("              ")

#завд 13 Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в
#діапазоні від -5 до 5 та знайдіть добуток їх елементів
import numpy as np

#дві матриці 2x2 з випадковими цілими числами від -5 до 5
A = np.random.randint(-5, 6, (2,2))
B = np.random.randint(-5, 6, (2,2))

print("Матриця A:\n", A)
print("Матриця B:\n", B)

#поелементний добуток матриць
elementwise_product = A * B
print("Поелементний добуток A * B:\n", elementwise_product)
print("              ")

#завд 14 Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні
#від 1 до 10 та знайдіть найбільший елемент матриці
import numpy as np

#матриця 3x3 з випадковими цілими числами від 1 до 10
A = np.random.randint(1, 11, (3,3))
print("Матриця A:\n", A)

#найбільший елемент
max_element = np.max(A)
print("Найбільший елемент матриці:", max_element)
print("              ")

#завд 15 Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в
#діапазоні від -1 до 1 та знайдіть вектор
import numpy as np

#матриця 4x4 з випадковими дійсними числами від -1 до 1
A = np.random.uniform(-1, 1, (4,4))
print("Матриця A (4x4):\n", A)

#кількість від'ємних елементів у кожному рядку
neg_counts = np.sum(A < 0, axis=1).reshape(-1,1)
print("Вектор кількості від'ємних елементів у кожному рядку:\n", neg_counts)
print("              ")

print("Висновок")
# У цій лабораторній роботі:
# - створила матриці та вектори різних розмірів
# - заповнила їх випадковими цілими та дійсними числами
# - виконала поелементні операції, матричне множення, транспонування та знаходження оберненої матриці
# - обчислила суми діагоналей та знаходити максимальні елементи
# - підраховувала специфічні властивості матриць (наприклад, кількість від'ємних елементів у рядках)


Масив кубів натуральних чисел:
[   1    8   27   64  125  216  343  512  729 1000]
              
Матриця 3x3 з факторіалами чисел від 1 до 9:
[[     1      2      6]
 [    24    120    720]
 [  5040  40320 362880]]
              
Матриця:
 [[-1  5  4]
 [ 4  5 -2]
 [ 3  5 -4]]
Сума модулів кожного рядка: [10 11 12]
              
Матриця:
 [[0.09931321 0.12007187 0.61673857]
 [0.10642992 0.77622691 0.49998796]
 [0.17055551 0.55380559 0.82689318]]
Середнє геометричне всіх елементів: 0.30629301902098227
              
Масив a: [0.00971756 0.3018013  0.26394237 0.61425726 0.26004505]
Масив b: [0.60280995 0.11774511 0.72705132 0.24193345 0.47698041]
Додавання: [0.61252751 0.41954641 0.99099369 0.85619071 0.73702546]
Віднімання: [-0.59309239  0.1840562  -0.46310895  0.37232381 -0.21693536]
Множення: [0.00585784 0.03553563 0.19189965 0.14860938 0.1240364 ]
              
Матриця A:
 [[2 2 3]
 [5 1 3]
 [2 2 2]]
Матриця B:
 [[3 5 5]
 [4 4 1]
 [5 4 3]]
Добуток A * B:
 [[29 30 21]
 [34 41 35]
 [